// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvuK7BQx34uU4RyUSZfKDGBoibjKGvOc',
    appId: '1:406738909292:web:b52cdd33a828e0e104c049',
    messagingSenderId: '406738909292',
    projectId: 'firedesk-4c38e',
    authDomain: 'firedesk-4c38e.firebaseapp.com',
    storageBucket: 'firedesk-4c38e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCynhO9JrSKYYzWxEIGH9lMbkoHXJ2yis',
    appId: '1:406738909292:android:c255c8b57a23ad0004c049',
    messagingSenderId: '406738909292',
    projectId: 'firedesk-4c38e',
    storageBucket: 'firedesk-4c38e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_fpBBQ5WYoNx5oZnqNbuG6LJT7hZ8mw',
    appId: '1:406738909292:ios:80f67b506165003a04c049',
    messagingSenderId: '406738909292',
    projectId: 'firedesk-4c38e',
    storageBucket: 'firedesk-4c38e.firebasestorage.app',
    iosBundleId: 'com.liestung.firedesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_fpBBQ5WYoNx5oZnqNbuG6LJT7hZ8mw',
    appId: '1:406738909292:ios:de95020c6145e36604c049',
    messagingSenderId: '406738909292',
    projectId: 'firedesk-4c38e',
    storageBucket: 'firedesk-4c38e.firebasestorage.app',
    iosBundleId: 'com.example.firedesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnvuK7BQx34uU4RyUSZfKDGBoibjKGvOc',
    appId: '1:406738909292:web:29b78651a770b34304c049',
    messagingSenderId: '406738909292',
    projectId: 'firedesk-4c38e',
    authDomain: 'firedesk-4c38e.firebaseapp.com',
    storageBucket: 'firedesk-4c38e.firebasestorage.app',
  );
}
